name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout código
        uses: actions/checkout@v4

      - name: Validar aplicação
        run: |
          python -m py_compile main.py

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

      - name: Simular Deploy
        run: |
          echo "Deploy realizado com sucesso"