name: Continuous Integration

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Validar sintaxe
        run: |
          python -m py_compile main.py

  test:

    needs: build

    runs-on: ubuntu-latest

    steps:

      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Executar testes
        run: |
          pytest tests/